chain_base_indent = "Visual"
chain_indent = "Visual"
fn_args_density = "Compressed"
fn_single_line = true
max_width = 79
reorder_imported_names = true
report_fixme = "Always"
single_line_if_else_max_width = 0
